package com.github.adinsa.picevolve.evolution;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.IntStream;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.github.adinsa.picevolve.expression.Expression;
import com.github.adinsa.picevolve.expression.ExpressionParser;
import com.github.adinsa.picevolve.expression.FunctionSet;

/**
 * Drives the genetic algorithm: generates random populations and produces new generations via mutation and crossover.
 *
 * @author amar
 *
 */
public class Evolver {

    private static final Logger logger = LoggerFactory.getLogger(Evolver.class);

    private static final int MAX_ATTEMPTS_PER_MEMBER = 1000;

    private final FunctionSet functions;
    private final ExpressionParser parser;
    private final Random random;

    public Evolver() {
        functions = FunctionSet.createDefault();
        parser = new ExpressionParser(functions);
        random = new RandomImpl(functions);
    }

    public Evolver(final Random random) {
        functions = FunctionSet.createDefault();
        parser = new ExpressionParser(functions);
        this.random = random;
    }

    public ExpressionParser getParser() {
        return parser;
    }

    /**
     * Returns a population of random expressions
     *
     * @param populationSize
     * @return
     */
    public List<Expression> initializePopulation(final int populationSize) {

        validatePopulationSize(populationSize);

        final List<Expression> population = new ArrayList<>();
        IntStream.range(0, populationSize).forEach(i -> population.add(random.nextExpression()));

        return population;
    }

    /**
     * Returns new generation of expressions containing mutations of the provided parent expression.
     *
     * @param parent
     * @param populationSize
     * @return
     */
    public List<Expression> mutate(final Expression parent, final int populationSize) {

        validatePopulationSize(populationSize);

        final List<Expression> nextGeneration = new ArrayList<>();

        int attempts = 0;
        while (nextGeneration.size() < populationSize && attempts < populationSize * MAX_ATTEMPTS_PER_MEMBER) {
            attempts++;
            final Mutator mutator = new Mutator(random);
            final Expression mutant = parser.parse(parent.toString());
            mutant.accept(mutator);

            if (!mutant.toString().equalsIgnoreCase(parent.toString())) {
                nextGeneration.add(mutant);
            }
        }

        return nextGeneration;
    }

    /**
     * Returns new generation of expressions generated by performing crossover between two provided parent expressions.
     *
     * @param mom
     * @param dad
     * @param populationSize
     * @return
     */
    public List<Expression> crossover(final Expression mom, final Expression dad, final int populationSize) {

        validatePopulationSize(populationSize);

        logger.debug("Mom expression: {}", mom.toString());
        logger.debug("Dad expression: {}", dad.toString());

        final List<Expression> children = new ArrayList<>();

        int attempts = 0;
        while (children.size() < populationSize && attempts < populationSize * MAX_ATTEMPTS_PER_MEMBER) {
            attempts++;
            Expression momCopy = parser.parse(mom.toString());
            final Expression dadCopy = parser.parse(dad.toString());

            final Expression momSubtree = random.nextNode(momCopy);
            final Expression dadSubtree = random.nextNode(dadCopy);

            if (momSubtree.getParent() == null) {
                momCopy = dadSubtree;
            } else {
                momSubtree.replaceWith(dadSubtree);
            }

            if (!momCopy.toString().equalsIgnoreCase(mom.toString())) {
                children.add(momCopy);
            }

        }

        return children;
    }

    private void validatePopulationSize(final int populationSize) {
        if (populationSize <= 0) {
            throw new IllegalArgumentException("Population size must be greater than zero: " + populationSize);
        }
    }
}
