package com.github.adinsa.picevolve;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.IntStream;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.github.adinsa.picevolve.expression.Expression;
import com.github.adinsa.picevolve.random.Random;
import com.github.adinsa.picevolve.random.RandomImpl;
import com.github.adinsa.picevolve.visitor.EvaluatorVisitor;
import com.github.adinsa.picevolve.visitor.MutationVisitor;
import com.github.adinsa.picevolve.visitor.Visitor;

public class PicEvolve {

    private static final Logger logger = LoggerFactory.getLogger(PicEvolve.class);

    private static final int MAX_ATTEMPTS_PER_MEMBER = 1000;

    private final FunctionSet functions;
    private final Random random;

    public PicEvolve() {
        functions = FunctionSet.createDefault();
        random = new RandomImpl(functions);
    }

    public PicEvolve(final Random random) {
        functions = FunctionSet.createDefault();
        this.random = random;
    }

    public FunctionSet getFunctionSet() {
        return functions;
    }

    /**
     * Parse the input s-expression string and return the AST as an {@link Expression}.
     *
     * @param expressionString
     * @return
     */
    public Expression parse(final String expressionString) {
        return functions.parse(expressionString);
    }

    /**
     * Returns a population of random expressions
     *
     * @param populationSize
     * @return
     */
    public List<Expression> initializePopulation(final int populationSize) {

        validatePopulationSize(populationSize);

        final List<Expression> population = new ArrayList<>();
        IntStream.range(0, populationSize).forEach(i -> population.add(random.nextExpression()));

        return population;
    }

    /**
     * Returns new generation of expressions containing mutations of the provided parent expression.
     *
     * @param parent
     * @param populationSize
     * @return
     */
    public List<Expression> mutate(final Expression parent, final int populationSize) {

        validatePopulationSize(populationSize);

        final List<Expression> nextGeneration = new ArrayList<>();

        int attempts = 0;
        while (nextGeneration.size() < populationSize && attempts < populationSize * MAX_ATTEMPTS_PER_MEMBER) {
            attempts++;
            final Visitor visitor = new MutationVisitor(random);
            final Expression mutant = parse(parent.toString());
            mutant.accept(visitor);

            if (!mutant.toString().equalsIgnoreCase(parent.toString())) {
                nextGeneration.add(mutant);
            }
        }

        return nextGeneration;
    }

    /**
     * Returns new generation of expressions generated by performing crossover between two provided parent expressions.
     *
     * @param mom
     * @param dad
     * @param populationSize
     * @return
     */
    public List<Expression> crossover(final Expression mom, final Expression dad, final int populationSize) {

        validatePopulationSize(populationSize);

        logger.debug("Mom expression: {}", mom.toString());
        logger.debug("Dad expression: {}", dad.toString());

        final List<Expression> children = new ArrayList<>();

        int attempts = 0;
        while (children.size() < populationSize && attempts < populationSize * MAX_ATTEMPTS_PER_MEMBER) {
            attempts++;
            Expression momCopy = parse(mom.toString());
            final Expression dadCopy = parse(dad.toString());

            final Expression momSubtree = random.nextNode(momCopy);
            final Expression dadSubtree = random.nextNode(dadCopy);

            if (momSubtree.getParent() == null) {
                momCopy = dadSubtree;
            } else {
                momSubtree.replaceWith(dadSubtree);
            }

            if (!momCopy.toString().equalsIgnoreCase(mom.toString())) {
                children.add(momCopy);
            }

        }

        return children;
    }

    private void validatePopulationSize(final int populationSize) {
        if (populationSize <= 0) {
            throw new IllegalArgumentException("Population size must be greater than zero: " + populationSize);
        }
    }

    /**
     * Evaluates input {@link Expression} into an {@link Image} whose values are normalized between 0 and 1.
     *
     * @param expression
     * @param width
     * @param height
     * @return
     */
    public Image evaluate(final Expression expression, final int width, final int height) {

        final EvaluatorVisitor visitor = new EvaluatorVisitor(width, height);
        expression.accept(visitor);

        return visitor.getImage().scaled();
    }
}
